# Generated by Django 6.0.3 on 2026-03-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_Item',
            new_name='CartItem',
        ),
        migrations.RenameModel(
            old_name='Order_Item',
            new_name='OrderItem',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
