# Generated by Django 6.0.3 on 2026-03-29 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_cart_item_cartitem_and_more'),
    ]

    operations = [
            migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ("collection1")
        """, """
            DELETE FROM store_collection 
            WHERE title= "collection1"
        """)
    ]
