# Generated by Django 6.0.3 on 2026-03-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tagged_Item',
            new_name='TaggedItem',
        ),
    ]
